### ISSUE TITLE
[3.6.1] substitution with english name in source and alt+r function

### ISSUE THREAD

**Issue by TokcDK** [bbepis/XUnity.AutoTranslator#39] opened 2019-07-01 13:18 UTC
About substitutions.
For example we have next source-translation pair in cache: **がんばれ、遥=Do your best, Haruka**
This phrase can be used many times in game and with different name and if source all in japanese then substitution rule **遥=Haruka** will be working with **がんばれ、{{A}}=Do your best, {{A}}** but if name in source will be on english then substitution rule Haruka=Haruka will not be working with **がんばれ、{{A}}=Do your best, {{A}}** and **がんばれ、Haruka** will be translated as new.

Second thing is about alt+r translation reload from cache. After using this translation is becoming wrong for some record on current page. But this is minor thing because after page will be updated translation will become correct.

In all cases for tests was used v3.6.1 with Bepinex5 in com3d2.

**Comment by gravydevsupreme** [comment] 2019-07-01 15:52
Hello,

Please report if the following versions fixes the first issue.

For the second issue, could you be more specific about a translation being "wrong"?

 * Is it a translation? 
 * Is it a translation for something else? If so, was whatever this is a translation for, previously shown in this text field?
 * If possible, could you provide me with a simple place in COM3D2 where it occurs that is easy for me to get to and reproduce.

[XUnity.AutoTranslator-BepIn-5x-3.6.2-custom.zip](https://github.com/bbepis/XUnity.AutoTranslator/files/3346415/XUnity.AutoTranslator-BepIn-5x-3.6.2-custom.zip)

**Comment by TokcDK** [comment] 2019-07-01 17:17
Thanks, I will try and will check.

About minor second problem. It is translation. When in game for example Im reading some dialog for example npc Haruka and another usually looking(in com3d2 it is Name in 1st line and text from 3rd line) dialog was was translated and then I found something was wrong translated and then opened translation cache txt and corrected last saved there dialog then saved cache txt and then switched back to the game and reloaded translation by alt+r and then dialog text changed to corrected variant but name Haruka can be changed to John for example or in another window all name was changed to aaaaaaaa. After dialog window will be refreshed name will become correct again.

**Comment by TokcDK** [comment] 2019-07-01 18:54
Tested 3.6.2 and seems it is working for english names now.

About second problem. Bepinex has console log and in another time when problem was repeated I checked console and there was also records about YATranslator which also using in com3d2. I suppose this problem because some conflicts with YATranslator.

**Comment by gravydevsupreme** [comment] 2019-07-02 15:03
Great that substitutions now work properly.

As for the other issue, there's definitely a potential for the plugin to conflict with other translation plugins.

But I am pretty sure this issue can also happen without such conflicts, as I have seen something like this before in other games.

Usually it is related to toggling of the translation instead of reloading it. But I've simply ignored it up until this point because I was not sure what was causing it. I'll take another look.

**Comment by gravydevsupreme** [comment] 2019-07-02 20:45
So I looked a bit further into the second issue and managed to get it working in at least the game I was testing it in. 

You can try out the following version and report if you experience the second problem anymore.

[XUnity.AutoTranslator-BepIn-5x-3.6.2-custom2.zip](https://github.com/bbepis/XUnity.AutoTranslator/files/3352251/XUnity.AutoTranslator-BepIn-5x-3.6.2-custom2.zip)

**Comment by TokcDK** [comment] 2019-07-04 16:47
Tested several times. It seems with standart dialog forms it was fixed but still see it other window of com3d2 and there after alt+r all names is changing to Aaaaaaa and some other also changing to another. 
Still think other plugins can have effect on this but I didnt see any of them in Bepinex console log. In Com3d2 also exist EnglishUI dll which is using for interface elements translation and also found there IMGUITranslationLoader dll. 
Maybe if you will add some debug info messages in some parts of code and I will use it debug version and will share messages in time of the issue then maybe it will give something but currently only standart message from autotranslator.

**Comment by TokcDK** [comment] 2019-07-05 16:48
Tested some times again. Removed all other dlls of plugins which can translate something for test if issue will be repeated and it is still repeating in the same screen. And after alt+r all wrong values is loading from cache txt.

**Comment by gravydevsupreme** [comment] 2019-07-06 13:15
Perhaps you could tell me which windows are causing the trouble? If there is a window that is easy to get to from a completely "new game", that would be nice because it would be easy for me to test.

If you can provide a screenshot of said window, that would be helpful as well.

Until then you can try this version, although I do not think it solves the problems.

[XUnity.AutoTranslator-BepIn-5x-3.6.2-custom3.zip](https://github.com/bbepis/XUnity.AutoTranslator/files/3364705/XUnity.AutoTranslator-BepIn-5x-3.6.2-custom3.zip)

**Comment by TokcDK** [comment] 2019-07-06 19:22
Yeah it can be opened from new game. It is Maid management window.

**Comment by gravydevsupreme** [comment] 2019-07-07 08:15
Managed to replicate it and apparently it seems the version I sent yesterday also fixed the issue.

Can you confirm?

**Comment by TokcDK** [comment] 2019-07-07 17:44
Only planned to check customv3 because you said about it rather will not fix the issue but checked after your message and yes now there is no broken translation. Tried to use alt+r and nothing was broken in this time. Thank you.

**Comment by gravydevsupreme** [comment] 2019-07-07 17:51
Good to hear. In that case I will close this issue. Feel free to re-open if you find another place where it does not behave in the maid game.

I will probably release the next version sometime next week.

**Closed by gravydevsupreme** 2019-07-07 17:51 UTC

**Comment by TokcDK** [comment] 2019-07-07 19:15
ok
