### ISSUE TITLE
Copy to clipboard: missing punctuation, frequent line breaks and no spacing

### ISSUE THREAD

**Issue by DySQRD** [bbepis/XUnity.AutoTranslator#177] opened 2021-05-05 15:11 UTC
Hello ! I have noticed some problems while using the Copy to clipboard functionality : (please note I haven't changed any other parameter aside from this one)

The game I am playing is [World End Economica](https://store.steampowered.com/app/269250/WORLD_END_ECONOMiCA_episode01/) and I would like to extract japanese text from it to make Anki cards using a web texthooker and Yomichan. I do not intend to translate the game as it already has English translation, so I can just play both the japanese and english versions at the same time ! I really just want to get the kanjis easily.
At first I tried Textractor, but it has some problems running this game, namely that it doesn't remember hooks after reloading. XUnity worked immediately though !
(See [the issue from which I was adviced to use XUnity](https://github.com/Artikash/Textractor/issues/551))

As expected, when new text appears in-game, it is sent to clipboard in japanese (only when ja-en translation is activated though), but it is so without any kind of punctuation or spacing.
Sentences are also separated in packs of 6 when sent to clipboard, but this can be solved by maxing out text speed: now all the text is copied to clipboard... still without punctuation or spacing.
This also has another weird side effect : Yomichan doesn't detect **combinations** of kanjis, instead it just gives the info of each kanji one by one.
<img width="948" alt="2021-05-05 16_36_06-Texthooker" src="https://user-images.githubusercontent.com/74011531/117162039-b8c34e00-adc2-11eb-825e-21baaad3cd16.png">

However, when opening the in-game's backlog, all of it gets sent to clipboard with punctuation and spacing, although with no line break. **Yomichan works normally here**.
<img width="837" alt="2021-05-05 16_58_30-Texthooker" src="https://user-images.githubusercontent.com/74011531/117162581-2ff8e200-adc3-11eb-924c-8defd1a9932d.png">

I'm new to all the VN hooking and translating stuff so I don't really understand how all of this works... besides, I think I got unlucky with this game, it causes problems everywhere ! (but I really wanted to play this one in particular)
Anyhow, thank you in advance for your help !

**Comment by gravydevsupreme** [comment] 2021-05-05 17:08
The copy to clipboard functionality does preserve newlines and punctuation. It is copied to the clipboard whenever it replaces an original text with a translation.

I have no clue why it shows up like that to you. Could you try a different tool that listens to the clipboard and see if it is a problem in that as well? For example [Translation Aggregator](https://github.com/Sinflower/Translation-Aggregator), which I just tested it with and where it worked properly with newlines and all.

**Comment by DySQRD** [comment] 2021-05-05 18:32
Here's how TA shows the text copied to clipboard by XUnity :
<img width="395" alt="2021-05-05 20_24_31-Translation Aggregator 2019 08 22 r194 (Unofficial)" src="https://user-images.githubusercontent.com/74011531/117190745-19ad4f00-ade0-11eb-8556-f0950db91eb3.png">
Backlog works even better now as line breaks show up as they should !
<img width="382" alt="2021-05-05 20_24_57-Translation Aggregator 2019 08 22 r194 (Unofficial)" src="https://user-images.githubusercontent.com/74011531/117191260-a526e000-ade0-11eb-970a-3ba800802352.png">
What do you think ? Does it come from the game or XUnity ?
Textractor did copy the text properly, but it was a pain to get it to work with World End Economica.

**Comment by gravydevsupreme** [comment] 2021-05-06 14:43
I do not have any ideas as to why this is happening. Would have to take a closer look at the game. But riddle me this: Does the same thing happen if you open the in-game translation aggregator (press ALT+1) or does that display the text correctly?

**Comment by DySQRD** [comment] 2021-05-06 15:35
@gravydevsupreme Ah you reminded me of something else I should have mentioned earlier. I was so preoccupied by the clipboard that I forgot about it, sorry for that.

As you can see on the image below characters are still shown individually, but another thing is the way dialogue is shown inside the textbox : these are the individual translation of each japanese character overlapping each other.
Sometimes some japanese characters don't disappear from the text boxes, not sure what triggers this.

<img width="960" alt="2021-05-06 17_16_56-" src="https://user-images.githubusercontent.com/74011531/117323550-48363300-ae8f-11eb-9efc-5357ff3772ff.png">

And this is the backlog : here the translation aggregator works fine (first image), AT THE CONDITION that the backlog is loaded from an already saved game. So if I start a new game, the translation aggregator will show the same thing as in the text boxes when opening the backlog (second image).

<img width="960" alt="2021-05-06 17_24_09-WORLD END ECONOMiCA episode 01" src="https://user-images.githubusercontent.com/74011531/117325562-1e7e0b80-ae91-11eb-8355-398349e7599c.png">

<img width="960" alt="2021-05-06 17_31_17-" src="https://user-images.githubusercontent.com/74011531/117325426-fee6e300-ae90-11eb-954d-d4a533066c52.png">

SOMETIMES, the text that is written in the backlog is replaced by its english translation, but I don't know what triggers it and can't get it to work right now.

**Comment by gravydevsupreme** [comment] 2021-05-07 14:16
Oh dear.

So it appears this game uses a separate text UI-components for each character. Likely because it tries to simulate a "scrolling-in" effect. But that will never work properly with this plugin because it expects the text to be displayed in a single component.

**Comment by DySQRD** [comment] 2021-05-07 14:48
> Oh dear.
> 
> So it appears this game uses a separate text UI-components for each character. Likely because it tries to simulate a "scrolling-in" effect. But that will never work properly with this plugin because it expects the text to be displayed in a single component.

I think I understand. Can another version of XUnity solve this problem at the moment ?

**Comment by gravydevsupreme** [comment] 2021-05-08 08:48
No. The plugin has always required there to be one text component per sentence or similar. This way to display text is incredibly game-specific and borderline impossible to implement in a game-agnostic fashion.

**Comment by gravydevsupreme** [comment] 2021-05-18 15:26
Closing this issue due to the specific nature of the problem and because the cause is close to unsolvable.

**Closed by gravydevsupreme** 2021-05-18 15:26 UTC
