### ISSUE TITLE
patch that disables the binding for the Japanese locale. 

### ISSUE THREAD

**Issue by dima245** [bbepis/XUnity.AutoTranslator#157] opened 2021-02-05 15:49 UTC
эти японцы. совсем обнаглели.
создают уже не одну игру на юнити с привязкой к японской локали . 
 без переключения на японскую локаль не удается начать игровой процес, при этом текст отображается нормально.
примеры игр :
RJ314694 SEXY DUNGEON [JP EN]
RJ274044 Magic_Sword_Incubus_HIXO2V6
ктоб смог создать патч отключающюю привязку к японской локали.

translate.google
these are Japanese. completely insolent.
create more than one game on a unity with reference to the Japanese locale.
  without switching to the Japanese locale, the gameplay cannot start and the text is displayed normally.
examples of games:
RJ314694 SEXY DUNGEON [JP EN]
RJ274044 Magic_Sword_Incubus_HIXO2V6
to be able to create a patch that disables the binding for the Japanese locale.

**Comment by gravydevsupreme** [comment] 2021-02-06 11:46
Locale issues are caused by inconsistencies between the text encoding used by the game/program and the OS/file system.

I assure you these types of issues are not caused by any type of ill will by Japanese people. It's simply that these types of games are generally developed and tested on a Japanese version of Windows (with JA locale). 

Either way there are already solutions that tries to fix this, such as NTLEA, AppLocale and Locale Emulator, etc.

**Comment by gravydevsupreme** [comment] 2021-02-07 11:09
Closing this, as this is not within the scope of this plugin.

**Closed by gravydevsupreme** 2021-02-07 11:09 UTC
