### ISSUE TITLE
The version of BepInEx can be translated normally in the game but cannot be used to call up the UI with alt+0

### ISSUE THREAD

**Issue by swarn1** [bbepis/XUnity.AutoTranslator#527] opened 2024-04-26 04:31 UTC
Why do I use the BepInEx version, which can translate normally in the game, but alt+0 cannot call up the interface, and I can only change the translator through config file.

**Comment by swarn1** [comment] 2024-04-26 04:41
Looking through the debug log, I only saw this error [Error  :XUnity.AutoTranslator] An error occurred in Update callback. 
System.InvalidOperationException: You are trying to read Input using the UnityEngine.Input class, but you have switched active Input handling to Input System package in Player Settings.

**Comment by Leowolf93** [comment] 2024-04-28 05:40
save question.

**Comment by ManlyMarco** [comment] 2024-06-19 17:57
Duplicate of #329

**Closed by ManlyMarco** 2024-06-19 17:57 UTC
