### ISSUE TITLE
Batch hooking

### ISSUE THREAD

**Issue by Cerzs** [bbepis/XUnity.AutoTranslator#48] opened 2019-08-20 00:31 UTC
Hi again! 

I was wondering, is there any way of hooking all the text for manual translation? Because many games has routes.

Thanks.

**Comment by gravydevsupreme** [comment] 2019-08-22 15:07
The way the translator works is essentially by trying to hook test as it is being displayed to the screen by knowing the UI components that are often used in Unity games, which means that something like this is very far from what the translator can do.

I am currently looking into implementing some functionality in relation redirecting resource files so they can be overridden/translated before they are used for the UI.

But even with this feature, something like this would probably require specialized implementation per game, although it perhaps could be generalized for something like Utage.

**Comment by Cerzs** [comment] 2019-08-22 18:20
I see. I think would be really useful because there are visual novels very, very long and seems a bit impossible to do a manual hooking.

**Comment by gravydevsupreme** [comment] 2019-08-31 22:38
Out of curiosity, what game are we talking about here? Since I implemented the resource redirector into this plugin I would be curious to see if it can intercept resources for the game in question.

**Comment by Cerzs** [comment] 2019-09-01 18:18
@gravydevsupreme [Our World is Ended](https://vndb.org/v21261), but most novels are like this.

**Comment by Cerzs** [comment] 2019-09-10 07:13
@gravydevsupreme fast question, any way to change windows name?

![imagen](https://user-images.githubusercontent.com/44489935/64591914-e56a5c80-d378-11e9-9d9c-5f82f89249ce.png)

**Comment by gravydevsupreme** [comment] 2019-09-10 15:20
The fast answer would be no. I don't really think this is a part of the Unity API, but it can probably be changed through Win32 API.

Something along the lines of this:

https://answers.unity.com/questions/148723/how-can-i-change-the-title-of-the-standalone-playe.html

**Comment by Cerzs** [comment] 2020-05-09 06:53
@gravydevsupreme Didn't want to open another issue. Can you tell me if it's possible to redirect the textures of Unity games that use ".dat" files?

Game UI is here: 
![imagen](https://user-images.githubusercontent.com/44489935/81466441-b9b9a380-919f-11ea-9286-91f3eabd7d65.png)

But as expected, the plugin ignore those files.

**Comment by gravydevsupreme** [comment] 2020-05-09 23:30
The file format is really irrelevant here. `dat` files are usually just an indicating that it is a file that contains some arbitrary binary data that only the one who made it would understand.

But again, it is really irrelevant to the question. The texture part of this plugin does not work on files at all. It works on the textures after they are loaded into memory. Perhaps you can tell me:
 * What you have tried
 * What game it is

**Comment by Cerzs** [comment] 2020-05-09 23:37
I just tried to dump the textures for translation, but just dumps some useless UI parts. [This is the game](https://vndb.org/r66233).

**Comment by Cerzs** [comment] 2020-05-10 19:18
@gravydevsupreme also here's the log if you need it:

> [Info   :XUnity.AutoTranslator] Loaded XUnity.AutoTranslator into Unity [2018.2.19f1] game.
[Info   :XUnity.AutoTranslator] Attempting to load TextMesh Pro font from asset bundle.
[Info   :   BepInEx] Loading [XUnity Resource Redirector 1.1.2]
[Message:   BepInEx] Chainloader startup complete
[Info   :XUnity.AutoTranslator] Performing texture lookup during scene load...
[Info   :XUnity.AutoTranslator] Finished texture lookup (took 0 seconds)

**Comment by gravydevsupreme** [comment] 2020-05-14 19:03
Hello again and sorry for the delay. Been extremely busy lately and still am.

I tried out the game, and I can confirm it doesn't work properly in it. It might be using a custom UI system or similar.

At the moment I don't really have time to investigate why it doesn't work, though. Sorry.

**Comment by Cerzs** [comment] 2020-05-15 05:45
@gravydevsupreme thanks for letting me know anyway. I hope you can investigate it anytime soon.

**Comment by Cerzs** [comment] 2020-05-15 08:05
@gravydevsupreme I found something, but idk if this helps. FromImageData works, but all the files are being extracted as "unnamed [CRC]", original files are WEBP, maybe that's why? FromImageData, as the documentation says, causes a noticeable performance issue.

**Comment by gravydevsupreme** [comment] 2020-05-15 14:30
I see. The plugin uses the name of the resource to lookup the translation. But if there is no name this is impossible. So the only other option is to do it based on the actual image data. 

I don't think that this would be related to the original file format, but rather how the game is implemented (if the images are stored in a arbitrary binary file, it would be up to the developer to actually set the image name of the generated texture).

**Comment by Cerzs** [comment] 2020-05-15 17:18
@gravydevsupreme but I still don't understand why it can't find the images when they do have names.
![imagen](https://user-images.githubusercontent.com/44489935/82077858-1b04d980-96ae-11ea-842a-12e6d28bde7a.png)

**Comment by gravydevsupreme** [comment] 2020-05-16 15:31
The file format that is use (.dat) is not something that is inherently understood by Unity. So it is probably developer that parses the files and manually loads those files into Textures generated in script. The developer then "forgets" to set the name of the texture because he doesn't really need that name for anything anyway.

When unity loads images through more "standard" means the name of the texture is automatically set by the Unity Engine so the developer doesn't have to.

This is likely what is happening here.

**Comment by Cerzs** [comment] 2020-05-16 17:46
Oh, I see. Then I'll have to work with FromImageData... Do you have any advice to reduce the lag impact? The game has 4K images, I think that causes more lag than it should, @gravydevsupreme

**Comment by gravydevsupreme** [comment] 2020-05-16 21:56
I'm afraid not. I can only think of the following ways to identity a Texture2D in Unity:
 * By it's resource name. (there may be duplicates, and some may not have names)
 * By it's image data. (certainly unique, but slow)
 * By it's placement in the game object hierarchy. (all will generally have a path, but the different paths can reference the same image leading to lots of duplicates, especially for atlas/sprite textures. (also game objects using the texture may be moved around in the hierarchy)). Would require a lot of manual configuration and as such has not been implemented.

Been spending a lot of time in the Unity Editor lately (also part of the reason why I am busy), but even the knowledge I gained from that does not suggest other ways of doing this.

**Comment by Cerzs** [comment] 2020-05-16 22:11
Mmm, I see, thanks for clearing it up. My last question would be about redirecting videos, the opening for example, can the plugin replace it?

**Comment by gravydevsupreme** [comment] 2020-05-17 15:26
This is not supported at the moment, no.

**Comment by gravydevsupreme** [comment] 2021-02-07 11:32
Closing the **original** issue described here, as that is basically impossible to support.

**Closed by gravydevsupreme** 2021-02-07 11:32 UTC
