### ISSUE TITLE
Add support for translator DeepL. (The Best)

### ISSUE THREAD

**Issue by gapculy** [bbepis/XUnity.AutoTranslator#43] opened 2019-08-03 02:21 UTC

**Comment by gapculy** [comment] 2019-08-03 02:23
Pls Add support for translator DeepL.
I've translated games with this translator and it's the most accurate.

**Comment by gravydevsupreme** [comment] 2019-08-10 10:46
Closing this as it is a duplicate of #36 

See my answer to the issue there.

**Closed by gravydevsupreme** 2019-08-10 10:46 UTC
