### ISSUE TITLE
A question about translation with numbers

### ISSUE THREAD

**Issue by Tzigan** [bbepis/XUnity.AutoTranslator#171] opened 2021-04-18 04:52 UTC
The game has a line and a lot of them where there are numbers that change either continuously or under certain conditions, you can how to make that numbers in these lines were skipped translator, but displayed on the screen, thus translating only the text in these lines, because the file is a lot of one-type string because of these numbers.

**Comment by gravydevsupreme** [comment] 2021-04-18 06:56
Right now there is only "manual" support for these types of situations through regexes. 

I do have an option that automatically templates out numbers for translations for a specific UI type to avoid potential spam issues. But that can only be used with that specific UI type right now. Would it be useful to make that configurable? (Note: It will certainly reduce quality of automated translations).

Example: 
 * Shown text in UI: `ヒットポイント: 89`
 * Generate translation: `ヒットポイント: {{A}}=Hit Points: {{A}}`

**Comment by Tzigan** [comment] 2021-04-18 07:01
Thank you, I think this feature would be nice if it could be customized, and the text I still adjust by hand as there are many inconsistencies in the auto-translation

**Comment by gravydevsupreme** [comment] 2021-04-19 21:10
There is no way to control it at the moment. But I may look into adding support for it through configuration.

**Comment by Tzigan** [comment] 2021-04-20 07:10
Я был бы благодарен если бы вы сделали поддержку этой функции. Заранее спасибо.

**Comment by gravydevsupreme** [comment] 2021-05-01 11:39
I made a new option, `TemplateAllNumbersAway`, that you can set to true in the configuration (the option will be added as false the first time start up the game).

Perhaps you can tell me if this works as expected?

[XUnity.AutoTranslator-BepIn-5x-4.16.0.zip](https://github.com/bbepis/XUnity.AutoTranslator/files/6409485/XUnity.AutoTranslator-BepIn-5x-4.16.0.zip)
[XUnity.AutoTranslator-ReiPatcher-4.16.0.zip](https://github.com/bbepis/XUnity.AutoTranslator/files/6409486/XUnity.AutoTranslator-ReiPatcher-4.16.0.zip)

**Comment by Tzigan** [comment] 2021-05-02 17:55
Thank you, I'll check and unsubscribe in a few days

**Comment by gravydevsupreme** [comment] 2021-05-04 14:39
Right. So as far as I can see there are two issues and I think both should be solvable:
 * Odd ZMCZ values persisted. This caused by a substitution technique that the plugin uses against an endpoint and likely the chosen endpoint changes their casing causing the plugin to fail the unsubstitution. This can easily be fixed by allowing the plugin to ignore casing.
 * The same variable used more than once.

Theoretically maybe it should also try to not split up numbers only split up by other control characters such as `:`.

**Comment by gravydevsupreme** [comment] 2021-05-04 15:10
About the line with rich text:

Although the plugin is capable of using translations with variables, it will not output such text, ever. A limitation.

Can be fixed handling it through a regex manually. If you increase set `MaxTextParserRecursion=3`, you may be able to get away with only creating a regex that handles the sub-part of the string `(Sol 01)`.

Something like:

`sr:"^\(([A-z]+) ([0-9]{2})\)$"=($1 $2)`

In which case it should generate translations for "Sol", etc., if those are considered translatable.

**Comment by gravydevsupreme** [comment] 2021-05-04 20:34
Please try this version, I think it should handle these situations better (although I have not tested it well):

[XUnity.AutoTranslator-BepIn-5x-4.16.0.zip](https://github.com/bbepis/XUnity.AutoTranslator/files/6423765/XUnity.AutoTranslator-BepIn-5x-4.16.0.zip)

**Comment by gravydevsupreme** [comment] 2021-05-04 20:34
Have not fixed duplicate variables of the same name yet, though.

**Comment by gravydevsupreme** [comment] 2021-05-05 21:32
Riiiight, so please forget about the previous version I provided and use this instead, the previous one had some basic stupid mistakes upon actual proper testing. Sorry about that.

[XUnity.AutoTranslator-BepIn-5x-4.16.0.zip](https://github.com/bbepis/XUnity.AutoTranslator/files/6430348/XUnity.AutoTranslator-BepIn-5x-4.16.0.zip)

**Comment by Tzigan** [comment] 2021-05-06 10:20
Good afternoon, in principle the robot works much better and almost as expected, the strings are now normally substituted variables without these characters:
`Zmcz` 
`{{A}}%={{A}}%`
`{{A}} Combat\n{B}} Science\n{C}} Engineering={{A}} Combat {{B}} Science {{C}} Engineering`
but the delimiters are missing, it's not a problem in principle and you can put them manually
Also, I failed to substitute the variable in the line, it also constantly copies it:
`Tsygan <color%3D#C5C5C0>(Sol 01)</color>= Tsygan <color%3D#C5C5C0>(SOL 01)</color>`
but it might be because you have very little experience with regular expressions.

**Comment by gravydevsupreme** [comment] 2021-05-06 14:32
This should fix the slope issue, and probably some other issues as well:

[XUnity.AutoTranslator-BepIn-5x-4.16.0.zip](https://github.com/bbepis/XUnity.AutoTranslator/files/6435376/XUnity.AutoTranslator-BepIn-5x-4.16.0.zip)

Can't really say much about the regex for now as I have not tested it in a game.

**Comment by Tzigan** [comment] 2021-05-06 20:46
Tested this version, but particularly did not go into the test, although I received a lot of data with string translations, now everything works as expected did not notice any deviations, about this line:
`Tsygan <color%3D#C5C5C0>(Sol 01)</color>= Tsygan <color%3D#C5C5C0>(SOL 01)</color>`
So far I can not say anything, I need more time because the day is very long and you can not scroll through the time.
Also in the line:
`{{A}} Combat{n{B}} Science{n{C}} Engineering={{A}} Combat {{B}} Science {{C}} Engineering`
the line break is still not done.
and also with the latest update of this translator other problems are gone

**Comment by gravydevsupreme** [comment] 2021-05-07 14:10
The linebreaks is cleanup you will have to perform yourself. They were likely removed by the translation endpoint as part of the translation.

**Comment by Tzigan** [comment] 2021-05-07 21:51
This is not critical, you can correct it manually, it is possible because of the google translator 
If I find any other problems with the program I will write here too

**Comment by gravydevsupreme** [comment] 2021-05-12 20:39
So the new version uploaded should now have a way of dealing with numbers like this. It is not entirely the same as I previously uploaded here, but fairly close.

Please do NOT write here if you find a new problem with this as I will not see it. Please open a new issue.

**Closed by gravydevsupreme** 2021-05-12 20:39 UTC

**Comment by Atamg1994** [comment] 2023-06-26 21:57
I still have problems and I wrote my translation server on node js
with a cache system and a solution that ignores html when translating and leaves it unchanged
https://github.com/bbepis/XUnity.AutoTranslator/issues/396
